Initial commit
This sets up a python application with uv and pre-commit.

There are two devcontainer configurations, one for docker and one for podman.
The podman configuration is untested.

```
Issues: permission error when installing rust packages.  Will troubleshoot in next commit.

× Failed to build `pendulum==3.0.0`
  ├─▶ The build backend returned an error
  ╰─▶ Call to `maturin.build_wheel` failed (exit status: 1)

      [stdout]
      Running `maturin pep517 build-wheel -i /home/vscode/.cache/uv/builds-v0/.tmpACmV49/bin/python --compatibility off`

      [stderr]
      💥 maturin failed
        Caused by: Cargo metadata failed. Does your crate compile with `cargo build`?
        Caused by: failed to start `cargo metadata`: Permission denied (os error 13)
        Caused by: Permission denied (os error 13)
      Error: command ['maturin', 'pep517', 'build-wheel', '-i', '/home/vscode/.cache/uv/builds-v0/.tmpACmV49/bin/python', '--compatibility', 'off'] returned non-zero exit status 1

      hint: This usually indicates a problem with the package or the build environment.
  help: `pendulum` (v3.0.0) was included because `cr8tor-publisher` (v0.1.0) depends on `pendulum`
```